### PR TITLE
Update 2-1.py

### LINKED ISSUE #5: Convertion image files to pdf
# Convertion image to pdf with PyPDF2
- [x] should find exact python module
- [x] should convert images to pdf.

### PR DESCRIPTION
**Pull request by GoldDragon1229**
I've converted tiff to jpg.

### CODE REVIEW

**Comment by GoldDragon1229** [comment]
I've completed convertion from tiff to jpg.

**Comment by OnlyDragon0403** [comment]
I've completed convertion between multi images and pdf.
I'll merge this PR.

**Comment by GoldDragon1229** [comment]
I've completed issue #5 by PR #8.

**Comment by OnlyDragon0403** [comment]
I've completed issue #5 by PR #8.

**Pull request merged**
